/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames_form;

import Database.Connect;
import Modele.Panneau;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Corine
 */
public class SaveBilb extends javax.swing.JDialog {

    /**
     * Creates new form SaveBilb
     */
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    public SaveBilb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPanneau = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbDim = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtAdr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbVille = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtClt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCamp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateDebut = new com.toedter.calendar.JDateChooser();
        lblEndDate = new javax.swing.JLabel();
        dateFin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaObserv = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(12, 2, 10, 12));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Location");
        getContentPane().add(jLabel12);
        getContentPane().add(jLabel10);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText("Panneau");
        getContentPane().add(jLabel4);

        cmbPanneau.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        cmbPanneau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRAVERSIERE", "SUPER-SIGN", "PANNEAU CLASSIQUE 6m*3m", "PANNEAU CLASSIQUE 4m*3m", "WALL SIGN", "PROXYS" }));
        cmbPanneau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPanneauActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPanneau);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel5.setText("Type");
        getContentPane().add(jLabel5);

        cmbType.setFont(new java.awt.Font("Times New Roman", 0, 19)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GIANTRY DOUBLE FACE - 1", "GIANTRY DOUBLE FACE - 2", "SUPER SIGN SINGLE FACE", "SUPER SIGN DOUBLE FACE", "CLASSIC SINGLE FACE", "CLASSIC DOUBLE FACE 1", "CLASSIC DOUBLE FACE 2", "ONE FACE", "DOUBLE FACE" }));
        getContentPane().add(cmbType);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel6.setText("Dimensions");
        getContentPane().add(jLabel6);

        cmbDim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbDim);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel7.setText("Adresse");
        getContentPane().add(jLabel7);

        txtAdr.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtAdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdrActionPerformed(evt);
            }
        });
        getContentPane().add(txtAdr);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setText("Ville");
        getContentPane().add(jLabel11);

        cmbVille.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmbVille.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bamenda", "Buea", "Douala", "Ekona", "Edea", "Ideneau", "Limbe", "Mamfe", "Maroua", "Muyuka", "Sangmelima" }));
        getContentPane().add(cmbVille);

        jLabel2.setText("Annonceur");
        getContentPane().add(jLabel2);

        txtClt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCltActionPerformed(evt);
            }
        });
        getContentPane().add(txtClt);

        jLabel1.setText("Campagne");
        getContentPane().add(jLabel1);

        txtCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampActionPerformed(evt);
            }
        });
        getContentPane().add(txtCamp);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel8.setText("date debut");
        getContentPane().add(jLabel8);
        getContentPane().add(dateDebut);

        lblEndDate.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblEndDate.setText("date fin");
        getContentPane().add(lblEndDate);
        getContentPane().add(dateFin);

        jLabel3.setText("Observations");
        getContentPane().add(jLabel3);

        txtAreaObserv.setColumns(20);
        txtAreaObserv.setRows(5);
        jScrollPane1.setViewportView(txtAreaObserv);

        getContentPane().add(jScrollPane1);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnAdd.setText("ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Connect db;
    private void txtAdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdrActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
//        StringBuilder warning = new StringBuilder();
////        Verify adress
//        if(txtAdr.getText().isEmpty()){
//            warning.append("Adress not be empty \n");
////            JOptionPane.showMessageDialog(this, "Adress not be empty", "Input Error", JOptionPane.WARNING_MESSAGE);
//        }else{
//            txtAdr.getText();
//        }
//        if(warning.length()>0){
//            JOptionPane.showMessageDialog(this, warning.toString(), "Input warning", JOptionPane.WARNING_MESSAGE);
//        } else{
//            try {
//                String sql = "INSERT INTO panneau(panneau, type, dimensions, adresse, ville, duree) VALUES(?,?,?,?,?,?)";
//                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_panneaux", "root", "");
//                ps = con.prepareStatement(sql);
//                Panneau bilb = new Panneau(0, cmbPanneau.getSelectedItem() + "", cmbType.getSelectedItem()+"", cmbDim.getSelectedItem()+"",
//                        txtAdr.getText(), cmbVille.getSelectedItem()+"", txtAreaObserv.getText());
//                JOptionPane.showMessageDialog(null, "inserted successfull");
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "erreur de saisis");
//            }
//        }
        
        
        try {
            String sql = "INSERT INTO panneau(panneau, type, dimensions, adresse, ville, duree) VALUES (?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestion_panneaux", "root", "");
            ps = con.prepareStatement(sql);
            ps.setString(1, (String) cmbPanneau.getSelectedItem());
            ps.setString(2, (String) cmbType.getSelectedItem());
            ps.setString(3, (String) cmbDim.getSelectedItem());
            ps.setString(4, txtAdr.getText());
            ps.setString(5, (String) cmbVille.getSelectedItem());
            ps.setString(6, txtAreaObserv.getText());
            ps.executeUpdate();
//            Panneau bilb = new Panneau(0, cmbPanneau.getSelectedItem() + "", cmbType.getSelectedItem()+"", cmbDim.getSelectedItem()+"",
//                    txtAdr.getText(), cmbVille.getSelectedItem()+"", txtAreaObserv.getText());
            JOptionPane.showMessageDialog(null, "inserted successfull");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de saisis");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtCltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCltActionPerformed

    private void txtCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampActionPerformed

    private void cmbPanneauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPanneauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPanneauActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        con = Connect.ConnectDB();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveBilb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveBilb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveBilb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveBilb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveBilb dialog = new SaveBilb(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbDim;
    private javax.swing.JComboBox<String> cmbPanneau;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JComboBox<String> cmbVille;
    private com.toedter.calendar.JDateChooser dateDebut;
    private com.toedter.calendar.JDateChooser dateFin;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JTextField txtAdr;
    private javax.swing.JTextArea txtAreaObserv;
    private javax.swing.JTextField txtCamp;
    private javax.swing.JTextField txtClt;
    // End of variables declaration//GEN-END:variables
}
